import Link from "next/link";
const data:Record<string,{title:string,eyebrow:string,desc:string,items:string[]}>={
 alerts:{title:"Local Alerts",eyebrow:"ALERT DESK",desc:"Important public updates, civic alerts and time-sensitive local information.",items:["Public notices","Road & transport alerts","Weather-related alerts","District advisories"]},
 education:{title:"Education",eyebrow:"EDUCATION DESK",desc:"Education news and useful information organised by district.",items:["Exams & results","Admissions","Schools & colleges","Scholarships"]},
 government:{title:"Government",eyebrow:"CIVIC DESK",desc:"Official notices, public services and government information.",items:["Official notices","Schemes & benefits","Public services","Recruitment"]},
 business:{title:"Local Business",eyebrow:"BUSINESS DESK",desc:"Discover useful businesses and services close to home.",items:["Local businesses","Services","Offers & listings","Business guides"]},
 weather:{title:"Weather",eyebrow:"WEATHER DESK",desc:"District-level weather information presented with clear sources and timestamps.",items:["District conditions","Rain alerts","Heat & weather advisories","Travel conditions"]}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return {title:data[slug]?.title||"OdiaDesk"}}
export default async function Category({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=data[slug];if(!d)return <main><section className="section"><div className="container prose"><h1>Not found</h1><Link href="/">Return home →</Link></div></section></main>;return <main><header className="header"><div className="container nav"><Link href="/" className="brand"><span className="brandmark">O</span><span><strong>Odia</strong>Desk<small>Your Odisha. Your Local Desk.</small></span></Link><Link href="/" className="textLink">← Home</Link></div></header><section className="pageHero"><div className="container"><span className="eyebrow">{d.eyebrow}</span><h1>{d.title.split(" ")[0]} <span>{d.title.split(" ").slice(1).join(" ")}</span></h1><p>{d.desc}</p></div></section><section className="section"><div className="container"><div className="categoryGrid">{d.items.map(x=><div className="categoryCard" key={x}><span>•</span><div><strong>{x}</strong><small>District-level information will appear here.</small></div><b>→</b></div>)}</div><div className="notice"><strong>Live data is the next build phase.</strong><p>OdiaDesk will connect these sections to verified official sources and editorial content rather than displaying invented information.</p></div></div></section></main>}